from __future__ import annotations

from pathlib import Path
from datetime import datetime
from fanuc_io_parser import IO_TYPES, iter_enabled

PORT_TYPE_CODES = {
    "DI": "io_din",
    "DO": "io_dout",
    "RI": "io_rdi",
    "RO": "io_rdo",
    "GI": "io_gpin",
    "GO": "io_gpout",
    "UI": "io_uopin",
    "UO": "io_uopout",
    "AI": "io_anin",
    "AO": "io_anout",
    "F":  "io_flag",
    "M":  "io_marker",
}


def karel_string(text: str, max_len: int = 40) -> str:
    clean = str(text or "").replace("'", "''")
    return clean[:max_len]


def generate_kl(data, output_path: str | Path, program_name: str = "loadiocmt") -> Path:
    path = Path(output_path)
    today = datetime.now().strftime("%d-%b-%y").upper()
    lines = []
    lines.extend(header(program_name, path.name, today))
    lines.extend([
        "%NOLOCKGROUP",
        "%ENVIRONMENT REGOPE",
        "%ENVIRONMENT IOSETUP",
        "",
        "%INCLUDE KLIOTYPS",
        "",
        "VAR",
        "  st : INTEGER",
        "",
        "---------------------------------------------------------------",
        "",
        f"BEGIN\t-- {program_name}",
        "",
    ])

    current = None
    for row in iter_enabled(data):
        if row.io_type != current:
            current = row.io_type
            lines.append(f"-- {current} Comments")
        comment = karel_string(row.comment)
        if row.io_type == "R":
            lines.append(f"  SET_REG_CMT({row.number}, '{comment}', st)")
        else:
            port = PORT_TYPE_CODES.get(row.io_type)
            if port is None:
                lines.append(f"  -- Unsupported type skipped: {row.io_type}[{row.number}] '{comment}'")
                continue
            lines.append(f"  SET_PORT_CMT({port}, {row.number}, '{comment}', st)")
        lines.append(f"  -- st <> 0 indicates {row.io_type}[{row.number}] comment was not set")
        lines.append("")

    lines.extend([
        f"END {program_name}",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def header(program_name: str, source_file: str, date_text: str) -> list[str]:
    return [
        f"PROGRAM {program_name}",
        "--    This material is the property of Darwin Day and  must  be  returned",
        "--    upon request.  This material and the information illustrated or",
        "--    contained herein may not be reproduced, copied, used, or transmitted",
        "--    in whole or in part in any way without the prior written consent of",
        "--    Darwin Day.",
        "--",
        "--    Program:",
        f"--\t\t\t\t{program_name}",
        "--",
        "--    Language: \t\t",
        "--\t\t\t\tKAREL",
        "--",
        "--    Source File:  ",
        f"--\t\t\t\t{source_file}   {date_text}",
        "--",
        "--    Description:",
        "--\t\t\t\tThis program loads FANUC robot I/O, flag, marker, and",
        "--\t\t\t\tregister comments generated by the DDay Controls FANUC",
        "--\t\t\t\tI/O Comment Tool.",
        "--",
        "--    Author: \t\t\t",
        "--\t\t\t\tDarwin Day",
        "--      \t4300 Rohr Rd",
        "--      \tOrion Township, Michigan    48359",
        "--",
        "--    Modification history:",
        "--",
        "------------------------------------------------------------------",
    ]
